#!/bin/bash

INSTALL_PATH=$(dirname -- "$( readlink -f -- "$0"; )")
BASHRC=/etc/bash.bashrc

while getopts ":u" option; do
 case $option in
   u) # install as user
     FONT_INSTALL_ARG="--user"
     BASHRC=~/.bashrc
     ;;
   esac
done

${INSTALL_PATH}/oh-my-posh font install ${FONT_INSTALL_ARG} NerdFontsSymbolsOnly

if ! grep -q "# added by init-bash" "${BASHRC}"; then
cat <<EOT >> ${BASHRC}
# added by init-bash
if [ -d /etc/bash.bashrc.d ]; then
  for i in /etc/bash.bashrc.d/*.sh; do
    if [ -r \$i ]; then
      . \$i
    fi
  done
  unset i
fi
# end

EOT
fi

